### ISSUE TITLE
10月1号开始,运行报错

### ISSUE THREAD

**Issue by only4freedom** [unwenliu/ddns_for_dynv6#1]
x509: certificate has expired or is not yet valid: current time 2021-10-10T08:20:15+08:00 is after 2021-09-30T14:01:15Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x662a73]

goroutine 1 [running]:
github.com/asmcos/requests.(*Response).Text(...)
        C:/Users/unwenliu/go/src/github.com/asmcos/requests/requests.go:287
main.res()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:102 +0x273
main.cronRequest()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:135 +0x26
main.main()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:146 +0x4ea

**Comment by honeway** [comment]
运行正常，但是过一会儿就异常了。
```
Get "https://dynv6.com/api/update?hostname=xxx&ipv6=xxx": dial tcp: lookup dynv6.com: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x373ce6]

goroutine 1 [running]:
github.com/asmcos/requests.(*Response).Text(...)
        C:/Users/unwenliu/go/src/github.com/asmcos/requests/requests.go:287
main.res()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:102 +0x286
main.cronRequest()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:137 +0x75
main.main()
        C:/Users/unwenliu/GolandProjects/ddns_for_dynv6/main.go:146 +0x4ea
```
